frr version 10.5.1
frr defaults traditional
hostname r2
no ipv6 forwarding
!
interface eth1
 description to r1
 ip address 10.0.12.2/30
!
interface eth2
 description to pc2
 ip address 192.168.2.1/24
!
ip route 192.168.1.0/24 10.0.12.1
!
line vty
!
